name: Tests

on:
  push:
    paths-ignore:
    - 'LICENSE'
    - '**.md'
    - 'examples/*'
    - 'templates/*'
  pull_request:
    paths-ignore:
    - 'LICENSE'
    - '**.md'
    - 'examples/*'
    - 'templates/*'

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: make get-deps

      - name: Build docker-gen
        run: make docker-gen

      - name: Check code formatting
        run: make check-gofmt

      - name: Run tests
        run: go test -v
